language: python

# Travis CI has no plans to support Python 2.4 and Jython.
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - pypy

script:
  - python setup.py install
  # Include the spec tests directory for Mustache spec tests and the
  # project directory for doctests.
  - pystache-test . ext/spec/specs
